version: '3.9'

services:
  orquestador:
    image: marcomadrid/orquestador:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - tienda_net
    depends_on:
      - usuarios-direcciones
      - productos-inventarios
      - ordenes-pagos

  usuarios-direcciones:
    image: marcomadrid/usuarios-direcciones:latest
    ports:
      - "8001:8000"
    volumes:
      - ./usuarios-direcciones/data:/programas/api-users/data
    env_file:
      - .env
    networks:
      - tienda_net

  productos-inventarios:
    image: marcomadrid/productos-inventarios:latest
    ports:
      - "8082:8000"
    volumes:
      - ./productos-inventario/data:/app/data
    env_file:
      - .env
    networks:
      - tienda_net

  ordenes-pagos:
    image: marcomadrid/ordenes-pagos:latest
    ports:
      - "8000:8000"
    volumes:
      - ./ordenes-pagos/data:/app/data
    env_file:
      - .env
    networks:
      - tienda_net

networks:
  tienda_net:
    driver: bridge
