openapi: 3.0.3
info:
  title: API de Productos e Inventario
  version: 1.0.0
  description: API para gestionar productos, inventario y categorías

servers:
  - url: http://localhost:8000
    description: Servidor local

paths:
  /products:
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto creado exitosamente

  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un producto por ID
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar un producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Producto actualizado correctamente
    delete:
      summary: Eliminar un producto
      responses:
        '200':
          description: Producto eliminado exitosamente

  /inventories:
    get:
      summary: Obtener inventario de productos
      responses:
        '200':
          description: Lista de inventario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inventory'
    post:
      summary: Registrar inventario de producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryInput'
      responses:
        '201':
          description: Inventario registrado exitosamente
  /inventories/{product_id}:
    parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener inventario por ID de producto
      responses:
        '200':
          description: Detalles del inventario
          content:
            application/json:
              schema:
                type: object
                properties:
                  product_id:
                    type: integer
                  quantity:
                    type: integer
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar cantidad del inventario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Inventario actualizado correctamente
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar entrada de inventario por ID
      responses:
        '200':
          description: Inventario eliminado correctamente
        '404':
          description: Producto no encontrado

  /categories:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Crear nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Categoría creada exitosamente

  /categories/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener una categoría por ID
      responses:
        '200':
          description: Detalles de la categoría
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Categoría no encontrada

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        category_id:
          type: integer
      required: [id, name, price, category_id]

    ProductInput:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
        category_id:
          type: integer
      required: [name, price, category_id]

    Inventory:
      type: object
      properties:
        product_id:
          type: integer
        quantity:
          type: integer
      required: [product_id, quantity]

    InventoryInput:
      type: object
      properties:
        product_id:
          type: integer
        quantity:
          type: integer
      required: [product_id, quantity]

    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required: [id, name]

    CategoryInput:
      type: object
      properties:
        name:
          type: string
      required: [name]
