openapi: 3.0.0
info:
  title: Microservicio Órdenes y Pagos
  version: 1.0.0
  description: API para gestionar órdenes de compra y pagos

servers:
  - url: http://localhost:8000

paths:
  /ordenes:
    get:
      summary: Listar todas las órdenes
      responses:
        '200':
          description: Lista de órdenes
    post:
      summary: Crear una nueva orden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario_id:
                  type: string
                productos:
                  type: array
                  items:
                    type: object
                    properties:
                      producto_id:
                        type: string
                      cantidad:
                        type: number
                total:
                  type: number
                estado:
                  type: string
      responses:
        '201':
          description: Orden creada
  /pagos:
    get:
      summary: Listar todos los pagos
      responses:
        '200':
          description: Lista de pagos
    post:
      summary: Crear un nuevo pago
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orden_id:
                  type: string
                metodo:
                  type: string
                monto:
                  type: number
                estado:
                  type: string
      responses:
        '201':
          description: Pago registrado
