openapi: 3.0.0
info:
  title: API de Inventario de Productos
  description: API para gestionar productos, inventario, categorías y proveedores
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Servidor de desarrollo

paths:
  /products:
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /product/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
    put:
      summary: Actualizar un producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Producto actualizado
    delete:
      summary: Eliminar un producto
      responses:
        '200':
          description: Producto eliminado

  /inventories:
    get:
      summary: Obtener todo el inventario
      responses:
        '200':
          description: Lista de registros de inventario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inventory'
    post:
      summary: Añadir registro de inventario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryInput'
      responses:
        '201':
          description: Registro de inventario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'

  /inventory/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
    put:
      summary: Actualizar cantidad en inventario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Inventario actualizado
    delete:
      summary: Eliminar registro de inventario
      responses:
        '200':
          description: Registro eliminado

  /categories:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Crear nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Categoría creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

  /category/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
    put:
      summary: Actualizar categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Categoría actualizada
    delete:
      summary: Eliminar categoría
      responses:
        '200':
          description: Categoría eliminada

  /suppliers:
    get:
      summary: Obtener todos los proveedores
      responses:
        '200':
          description: Lista de proveedores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
    post:
      summary: Crear nuevo proveedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierInput'
      responses:
        '201':
          description: Proveedor creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'

  /supplier/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
    put:
      summary: Actualizar proveedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierInput'
      responses:
        '200':
          description: Proveedor actualizado
    delete:
      summary: Eliminar proveedor
      responses:
        '200':
          description: Proveedor eliminado

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
        - id
        - name

    ProductInput:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    Inventory:
      type: object
      properties:
        id:
          type: integer
          format: int32
        product:
          type: string
        quantity:
          type: integer
          format: int32
      required:
        - id
        - product
        - quantity

    InventoryInput:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        cantidad:
          type: integer
          format: int32
      required:
        - productId
        - cantidad

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int32
        category_name:
          type: string
      required:
        - id
        - category_name

    CategoryInput:
      type: object
      properties:
        category_name:
          type: string
      required:
        - category_name

    Supplier:
      type: object
      properties:
        id:
          type: integer
          format: int32
        supplier_name:
          type: string
      required:
        - id
        - supplier_name

    SupplierInput:
      type: object
      properties:
        supplier_name:
          type: string
      required:
        - supplier_name
