version: '3.8'

services:
  microserviciopython:
    build: ./microserviciopython
    ports:
      - "5000:8000"
    volumes:
      - sqlite_data:/data

  microserviciojava:
    build: ./microserviciojava
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=admin

  db_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  sqlite_data:
  pgdata: