openapi: 3.0.3
info:
  title: API Orquestador - Tienda
  description: API que orquesta la obtención del resumen de una orden y sus pagos.
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Servidor local

paths:
  /resumen/{ordenId}:
    get:
      summary: Obtener resumen de compra
      description: Devuelve los detalles de la orden junto con los pagos asociados.
      parameters:
        - name: ordenId
          in: path
          required: true
          description: ID de la orden
          schema:
            type: string
      responses:
        '200':
          description: Resumen encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumenCompra'
        '404':
          description: Orden no encontrada
        '500':
          description: Error interno del servidor

components:
  schemas:
    Producto:
      type: object
      properties:
        producto_id:
          type: string
        cantidad:
          type: integer
        nombre:
          type: string
        precio_unitario:
          type: number
          format: float

    Orden:
      type: object
      properties:
        _id:
          type: string
        usuario_id:
          type: string
        productos:
          type: array
          items:
            $ref: '#/components/schemas/Producto'
        total:
          type: number
          format: float
        fecha:
          type: string
          format: date-time

    Pago:
      type: object
      properties:
        _id:
          type: string
        orden_id:
          type: string
        monto:
          type: number
          format: float
        fecha:
          type: string
          format: date-time

    ResumenCompra:
      type: object
      properties:
        orden:
          $ref: '#/components/schemas/Orden'
        pagos:
          type: array
          items:
            $ref: '#/components/schemas/Pago'
